apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-ops-agent-suite-secret-model-api-key
  namespace: customer-ops-agent-suite
  labels:
    app.kubernetes.io/name: customer-ops-agent-suite
    app.kubernetes.io/managed-by: ads-reference-processor
    ads.dev/target-profile: kubernetes-production
    ads.dev/requirement-type: secret-binding
  annotations:
    ads.dev/source-path: "$.secrets.required[0]"
data:
  name: model-api-key
  purpose: model-provider-auth
  source: external-secret-store
  ref: prod/support-agent/model-api-key
  bindingAvailable: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-ops-agent-suite-secret-database-url
  namespace: customer-ops-agent-suite
  labels:
    app.kubernetes.io/name: customer-ops-agent-suite
    app.kubernetes.io/managed-by: ads-reference-processor
    ads.dev/target-profile: kubernetes-production
    ads.dev/requirement-type: secret-binding
  annotations:
    ads.dev/source-path: "$.secrets.required[1]"
data:
  name: database-url
  purpose: session-state
  source: external-secret-store
  ref: prod/support-agent/database-url
  bindingAvailable: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-ops-agent-suite-secret-crm-api-token
  namespace: customer-ops-agent-suite
  labels:
    app.kubernetes.io/name: customer-ops-agent-suite
    app.kubernetes.io/managed-by: ads-reference-processor
    ads.dev/target-profile: kubernetes-production
    ads.dev/requirement-type: secret-binding
  annotations:
    ads.dev/source-path: "$.secrets.required[2]"
data:
  name: crm-api-token
  purpose: crm-tool-access
  source: external-secret-store
  ref: prod/customer-ops/crm-api-token
  bindingAvailable: 'true'
