apiVersion: v1
kind: ConfigMap
metadata:
  name: support-agent-secret-model-api-key
  namespace: support-agent
  labels:
    app.kubernetes.io/name: support-agent
    app.kubernetes.io/managed-by: ads-reference-processor
    ads.dev/target-profile: kubernetes-production
    ads.dev/requirement-type: secret-binding
  annotations:
    ads.dev/source-path: "$.secrets.required[0]"
data:
  name: model-api-key
  purpose: model-provider-auth
  source: external-secret-store
  ref: prod/support-agent/model-api-key
  bindingAvailable: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: support-agent-secret-database-url
  namespace: support-agent
  labels:
    app.kubernetes.io/name: support-agent
    app.kubernetes.io/managed-by: ads-reference-processor
    ads.dev/target-profile: kubernetes-production
    ads.dev/requirement-type: secret-binding
  annotations:
    ads.dev/source-path: "$.secrets.required[1]"
data:
  name: database-url
  purpose: session-state
  source: external-secret-store
  ref: prod/support-agent/database-url
  bindingAvailable: 'true'
